### ISSUE TITLE
[BUG] Notion API Error - Body Failed Validation

### ISSUE THREAD

**Issue by robfrizzy** [beetee17/Minutes#1]
**Describe the bug**

When attempting to export a summary to Notion Database I receive this error:

> Notion API Error
> body failed validation. Fix one: bodv.children.length should be ≤ 100', instead was 148 body.parent.page_id should be defined. instead was undefined

**To Reproduce**
1. Select Summary
2. Click on Title of Summary
3. Select “Export to [Notion Database]”
4. Error pop up appears

**Expected behavior**

I expected it to export the summary into my Notion database

**Screenshots**

**iOS (please complete the following information):**
 - Device: iPad Pro (12.9-inch) (4th generation)
 - OS: 16.4.1 (a)

**Additional context**

The transcription I am using is fairly long at almost 40 minutes in length.

**Comment by beetee17** [comment]
Hi Rob,

Thanks for the bug report. I think I've identified the issue: according to [Notion API's Request Limits Documentation](https://developers.notion.com/reference/request-limits), the request cannot contain more than 100 elements. This is definitely fixable by splitting the summary and sending multiple API requests. 

As a sanity check, could you try removing about the bottom half of the summary and then exporting it to Notion? Be sure to save a copy of the current version so you can revert it back afterward. 

Thanks again!

**Comment by beetee17** [comment]
Do try out the latest update (v1.0.6), the bug should have been resolved. 

Will be closing this issue for now, but let me know if it still persists on your end and I'll reopen the issue.
