### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by greiggy** [beetee17/Minutes#2]
**Describe the bug**
I am subscribed for a year. I checked under ‘Subscriptions’.

I only get the first part of a text transcript, although I can see the full transcript with time stamps. This makes it really difficult to export the content!

**To Reproduce**
2. Tap on '....'
From recorded file, select ‘text’ on top right pull-down then export and copy. Paste into other application.
**Expected behavior**

I expect a full length text transcript to be copied to clipboard and then pasted eg in a notes app. I have tried every way I know and I only get the first half.

Minutes could be improved by making this untimestamped output easier to access. At present I have to select ‘text’ from the tiny pull down at top right, then > export > copy. That’s clunky for a basic operation needed on every transcript!

**Screenshots**

**iOS (please complete the following information):**
 - Device: [e.g. iPhone 13]
 - OS: [e.g. iOS 16.1]
IPhone8+
iOS 16.6
**Additional context**
No, that’s about it.

**Comment by beetee17** [comment]
Hi greiggy,

Thanks for reaching out. Could I trouble you to check if the issue persists when performing the following actions: 

1. Navigate to one of the problematic transcript(s)
2. Tap the transcript’s title to present the dropdown menu
3. Tap the option labelled “Select”
4. Scroll through the sheet that is presented 
5. Verify that the transcript’s content is shown in full, or if only the first half is showing

Brandon

**Comment by greiggy** [comment]
Hi Brandon, I followed your instructions and I am only seeing half the transcript under 'Select'.

Definitely all there in the timestamped view.

-- IanG

**Comment by beetee17** [comment]
Thanks for checking in. Do the problematic transcript(s) all have word level timestamps? 

That is to say, your transcript looks like the one below:

![image](https://github.com/beetee17/Minutes/assets/81674501/e462acdc-48d3-402a-ba1d-51bbf86ae141)


As opposed to this (where the highlights are at the paragraph level):

![image](https://github.com/beetee17/Minutes/assets/81674501/3078a06b-b95a-48c3-be72-45856305d5d8)

This would help me narrow down the bug!

Brandon

**Comment by greiggy** [comment]
Hi Brandon,

Highlights at paragraph level -- like your 2nd screenshot

--IanG

**Comment by beetee17** [comment]
Hi greiggy,

Apologies for the delay, I was waiting for approval from Apple for the latest update.

I think I've resolved the bug, but I'd greatly appreciate it if you could confirm the fix on your end by installing the latest beta build.

To do so, please follow these steps:

1. Download TestFlight: If you haven't already, you can get it [here](https://apps.apple.com/us/app/testflight/id899247664).
2. Install the Beta: Use [this link](https://testflight.apple.com/join/5z25NHwR) to access the beta version. The exact build number is 2.0.2 (1).

Note that installing the TestFlight version will NOT overwrite any data, and you can simply switch back to the App Store version by installing it there. 

I look forward to hearing from you!

Brandon

**Comment by greiggy** [comment]
Hi Brandon,

I used the TestFlight version quite a bit today on short dictations — no problems.

I haven’t tested a longer one but I will have one coming up tomorrow!

Well done in getting that bug sorted.

—Ian Greig
UK user

**Comment by beetee17** [comment]
Hey Ian, thank you for the prompt reply, do keep me posted!

**Comment by greiggy** [comment]
Did some longer e.g. 5 min takes today and no reoccurrence of the partial transcript bug.

I would say, in passing and not related to that piece of work, that it is quite a faff to get text output from Minutes. However I do it, it takes a lot of keystrokes and sometimes I get a link to a text file and not the actual text.

It would be worth improving this because every transcription is a piece of text to go somewhere else on the workflow — and the workflow from Minutes takes a lot of key presses.

Ideally, one keystroke to ‘Copy plain text to clipboard’ or an auto email export as one of your competitors does.

All the best with your next update and thanks for sorting the partial text problem!

—Ian Greig
UK user

**Comment by beetee17** [comment]
Hey Ian, thanks again for confirming that the bug has been fixed! 

I will be pushing the update to the App Store and it should be released in a couple of days. As discussed, you can switch back to the App Store version without any loss of data just by installing it over there (note that the beta build will expire in less than 90 days).

Appreciate the feedback on the workflow. I assume you're aware that there is a button labelled "Copy" in the title menu dropdown which accomplishes the task in just 2 taps; am I right saying that you're asking for it to be even faster than that?

Brandon

**Comment by greiggy** [comment]
I overlooked the ‘Copy’ button which does produce non-timestamped text. Thanks for pointing that out — it works well.

Minutes seems to understand punctuation such as ‘New paragraph’ and ‘Open quotes’ during dictation but I do not see that in the text output.

A breakthrough in Whisper dictation/transcription would be to get Whisper to parse these simple punctuation commands. Whisper apps I have tried all have this weakness.

— Ian Greig
UK user

**Comment by beetee17** [comment]
Ah, I see what you mean. The reason for the discrepancy is that the live dictation uses Siri to provide a responsive experience, due to limitations of the current Whisper technology. 

It seems that Siri is able to detect keywords for punctuation, which would be great if I could somehow merge its output to produce an even higher quality transcript, but I'll have to look into how feasible that would be. 

Thanks for the feedback!
